### PR TITLE
app.py: Initial Setup

### PR DESCRIPTION
**Pull request by hemangsk**
templates: Added index.html

### CODE REVIEW

**Comment by hemangsk** [comment]
ack #30145e57109b8d0d78a854341eb0b2d433a4866c

**Comment by hemangsk** [comment]
@rultor merge

**Comment by meetmangukiya** [comment]
You even added a `__pycache__` folder @hemangsk by mistake

**Comment by hemangsk** [comment]
@meetmangukiya  yeah ! removed it  😄

**Pull request merged**
